/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author aluno
 */
public class TelaAgenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaAgenda
     */
    public TelaAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel6 = new javax.swing.JLabel();
        lblSO = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuContatos = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuTrocarUsuario = new javax.swing.JMenuItem();
        mnuTrocarSenha = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();
        mnuConfiguracoes = new javax.swing.JMenu();
        mnuSom = new javax.swing.JCheckBoxMenuItem();
        mnuTemas = new javax.swing.JMenu();
        mnuNimbus = new javax.swing.JCheckBoxMenuItem();
        mnuGTK = new javax.swing.JCheckBoxMenuItem();
        mnuMacOS = new javax.swing.JCheckBoxMenuItem();
        mnuAluminium = new javax.swing.JCheckBoxMenuItem();
        mnuWindows = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/agenda.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(getMaximumSize());
        jLabel1.setMinimumSize(getMinimumSize());

        jToolBar1.setRollover(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/0198.png"))); // NOI18N
        jLabel2.setText("Usuário:");
        jToolBar1.add(jLabel2);

        lblUsuario.setMaximumSize(new java.awt.Dimension(100, 16));
        lblUsuario.setMinimumSize(new java.awt.Dimension(100, 16));
        lblUsuario.setPreferredSize(new java.awt.Dimension(100, 16));
        jToolBar1.add(lblUsuario);
        jToolBar1.add(jSeparator2);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/0277.png"))); // NOI18N
        jLabel4.setText("Nível:");
        jToolBar1.add(jLabel4);

        lblNivel.setMaximumSize(new java.awt.Dimension(100, 16));
        lblNivel.setMinimumSize(new java.awt.Dimension(100, 16));
        lblNivel.setPreferredSize(new java.awt.Dimension(100, 16));
        jToolBar1.add(lblNivel);
        jToolBar1.add(jSeparator3);

        jLabel6.setText("S.O.:");
        jToolBar1.add(jLabel6);
        jLabel6.getAccessibleContext().setAccessibleName("jLabel6");

        lblSO.setMaximumSize(new java.awt.Dimension(100, 16));
        lblSO.setMinimumSize(new java.awt.Dimension(100, 16));
        lblSO.setPreferredSize(new java.awt.Dimension(100, 16));
        jToolBar1.add(lblSO);
        lblSO.getAccessibleContext().setAccessibleName("jLabel7");

        mnuCadastro.setText("Cadastro");

        mnuContatos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/0009.png"))); // NOI18N
        mnuContatos.setText("Contatos");
        mnuCadastro.add(mnuContatos);

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/0198.png"))); // NOI18N
        mnuUsuarios.setText("Usuários");

        mnuTrocarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/0009.png"))); // NOI18N
        mnuTrocarUsuario.setText("Trocar Usuário");
        mnuTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrocarUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuTrocarUsuario);

        mnuTrocarSenha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuTrocarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/0190.png"))); // NOI18N
        mnuTrocarSenha.setText("Trocar Senha");
        mnuTrocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrocarSenhaActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuTrocarSenha);

        mnuCadastro.add(mnuUsuarios);
        mnuCadastro.add(jSeparator1);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/0190.png"))); // NOI18N
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuSair);

        jMenuBar1.add(mnuCadastro);

        mnuConfiguracoes.setText("Configurações");

        mnuSom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSom.setSelected(true);
        mnuSom.setText("Som");
        mnuConfiguracoes.add(mnuSom);

        mnuTemas.setText("Temas");

        buttonGroup1.add(mnuNimbus);
        mnuNimbus.setText("Nimbus");
        mnuNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNimbusActionPerformed(evt);
            }
        });
        mnuTemas.add(mnuNimbus);

        buttonGroup1.add(mnuGTK);
        mnuGTK.setText("GTK+");
        mnuGTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGTKActionPerformed(evt);
            }
        });
        mnuTemas.add(mnuGTK);

        buttonGroup1.add(mnuMacOS);
        mnuMacOS.setText("Mac OS X");
        mnuMacOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMacOSActionPerformed(evt);
            }
        });
        mnuTemas.add(mnuMacOS);

        buttonGroup1.add(mnuAluminium);
        mnuAluminium.setText("Aluminium");
        mnuAluminium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAluminiumActionPerformed(evt);
            }
        });
        mnuTemas.add(mnuAluminium);

        buttonGroup1.add(mnuWindows);
        mnuWindows.setText("Windows");
        mnuWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWindowsActionPerformed(evt);
            }
        });
        mnuTemas.add(mnuWindows);

        mnuConfiguracoes.add(mnuTemas);

        jMenuBar1.add(mnuConfiguracoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(531, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuTrocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrocarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuTrocarSenhaActionPerformed

    private void mnuNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNimbusActionPerformed
        mudaLaf("javax.swing.plaf.nimbus.NimbusLookAndFeel");
    }//GEN-LAST:event_mnuNimbusActionPerformed

    private void mnuWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuWindowsActionPerformed
        mudaLaf("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
    }//GEN-LAST:event_mnuWindowsActionPerformed

    private void mnuAluminiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAluminiumActionPerformed
        mudaLaf("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
//        com.sun.java.swing.plaf.
    }//GEN-LAST:event_mnuAluminiumActionPerformed

    private void mnuGTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGTKActionPerformed
        mudaLaf("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
    }//GEN-LAST:event_mnuGTKActionPerformed

    private void mnuMacOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMacOSActionPerformed
        mudaLaf("com.apple.plaf.AquaLookAndFeel");
    }//GEN-LAST:event_mnuMacOSActionPerformed

    private void mnuTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrocarUsuarioActionPerformed
        TelaLogin telalogin = new TelaLogin(this, true);
        telalogin.setVisible(true);
    }//GEN-LAST:event_mnuTrocarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgenda().setVisible(true);
            }
        });
    }

    private void mudaLaf(String temaLaf){
        try{
            UIManager.setLookAndFeel(temaLaf);
            SwingUtilities.updateComponentTreeUI(this);
        } catch( ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            JOptionPane.showMessageDialog(null, "Tema não suportado neste S.O.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblSO;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JCheckBoxMenuItem mnuAluminium;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenu mnuConfiguracoes;
    private javax.swing.JMenuItem mnuContatos;
    private javax.swing.JCheckBoxMenuItem mnuGTK;
    private javax.swing.JCheckBoxMenuItem mnuMacOS;
    private javax.swing.JCheckBoxMenuItem mnuNimbus;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JCheckBoxMenuItem mnuSom;
    private javax.swing.JMenu mnuTemas;
    private javax.swing.JMenuItem mnuTrocarSenha;
    private javax.swing.JMenuItem mnuTrocarUsuario;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JCheckBoxMenuItem mnuWindows;
    // End of variables declaration//GEN-END:variables
}
